---
title: "Prueba 1"
author: "Constanza Valenzuela"
date: "2024-09-02"
output: 
  html_document: default

---

# Probabilidad clase 1 #
## The definition of probability requires the following concepts:##
* **experiment**: an action or a set of actions that produce stochastic events
of interest
* **sample space**: a set of all possible outcomes of the experiment, typically denoted by $\Omega$
* **event**: a subset of the sample space

##We now discuss how to compute probability, starting with the simplest case in which all outcomes are equally likely to occur. In this case, the probability of event A occurring, denoted by P (A), can be computed as the ratio of the number of elements
in the corresponding set A to that in the entire sample space
La fracción en bloque se escribe así:

$$
\frac{\text{number of elements in A}}{\text{number of elements in} \ \Omega}
$$

## The probability axioms are given by the following three rules:##

1. The probability of any event A is nonnegative:
$$
P (A) ≥ 0.
$$
2. The probability that one of the outcomes in the sample space occurs is 1:
$$
P (\Omega) = 1.
$$
3. (Addition rule) If events A and B are mutually exclusive, then
$$
P (A\ \text {or}\ B) = P (A) + P (B)
$$
##Los primeros dos axiomas se refieren a (0,1) y se refieren a ser "mutuamente excluyentes"##
![Newfile] ()